sudo: required
dist: trusty

language: node_js
node_js:
  - "7.5"

env:
  - MONGODB_VERSION=3.4.2
  - MONGODB_USER=travis
  - MONGODB_PASS=test

sevices:
  - mongodb

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 15
  - mongo chess --eval 'db.addUser("travis", "test")'
install:
  - npm install
script:
  - npm test
  - eslint src/**
