sudo: required
dist: trusty

language: node_js
node_js:
  - "7.5"

sevices:
  - mongodb

before_install:
  - export MONGO_HOST=localhost
  - export MONGO_USER=travis
  - export MONGO_PASS=test
  - sleep 15
  - mongo chess --eval 'db.addUser("travis", "test");'
install:
  - npm install
script:
  - npm test
  - eslint src/**
