language: node_js
node_js:
  - "7.5"

before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn test
  - eslint src/**
  - istanbul cover _mocha -- --recursive --require babel-polyfill --compilers js:babel-register && istanbul-coveralls && rm -rf ./coverage
