sudo: required
dist: trusty

language: node_js
node_js:
  - "7.5"

sevices:
  - mongodb

before_install:
  - export MONGO_HOST=localhost
  - export MONGO_PORT=27017
  - export MONGO_USER=travis
  - export MONGO_PASS=test
  - travis_retry "mongo chess --eval 'db.addUser(\"travis\", \"test\")'; sleep 3;"
install:
  - npm install
script:
  - npm test
  - eslint src/**
