language: node_js
sudo: required
sevices: mongodb

node_js:
  - "7.5"

before_install:
  - npm install -g yarn
  - export MONGO_HOST=localhost
install:
  - yarn
script:
  - yarn test
  - eslint src/**
